serviceAccount:
  create: true

secretName: slack-secret

config:
  events:
    hpa_scaling:
      type: Normal
      reason: SuccessfulRescale
      kind: HorizontalPodAutoscaler
      namespace: devdrill-prod

  fetchers:
    target_deployment:
      resource: Deployment
      namespace: devdrill-prod
      resource_name: devdrill-api

  notifiers:
    slack/alert-hpa:
      webhook_url: $SLACK_WEBHOOK_ALERT
      title: "🚀 [HPA Scaling] 이벤트 발생: {{ event.involvedObject.name }}"
      message: |
        - 현재 파드 수: {{ target_deployment.spec.replicas }}
      color: "#0077cc"

  service:
    pipelines:
      default_alert_pipeline:
        events: ["hpa_scaling"]
        fetchers: ["target_deployment"]
        notifiers: ["slack/alert-hpa"]
