apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      # ConfigMap이 변경되면 자동으로 파드를 재시작시키기 위한 어노테이션
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "kube-event-collector.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "bvv8808/kube-event-collector:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{- end }}
{{- if .Values.secretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
{{- end }}
