image:
  pullPolicy: IfNotPresent

logLevel: INFO

serviceAccount:
  create: true

# 외부에서 수동으로 생성한 Secret 이름
secretName: ""

# 환경변수로 직접 주입할 설정값들
env: {}

# 컨트롤러 파이프라인 엔진 설정 (ConfigMap의 Data로 직접 들어감)
config: {}
